### ISSUE TITLE
Labels in the sidebar overlap due to wrong CSS

### ISSUE THREAD

**Issue by ghost** [Perennials/jsdocgen#27]
Should be:

``` css
#DocBlockViewer-Sidebar .HtmlArea ul>li>.label.small {
z-index: 1;
float: right;
margin-right: 3px;
}
```

instead of

``` css
#DocBlockViewer-Sidebar .HtmlArea ul>li>.label.small {
z-index: 1;
position: absolute;
right: 3px;
}
```
